@Catalog.Api_HostAddress = http://localhost:5163

GET {{Catalog.Api_HostAddress}}/weatherforecast/
Accept: application/json

###
POST /api/categories
{
  "name": "Fiction",
  "description": "All fiction books"

}