@baseUrl = http://localhost:7000
@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjZjhmYTkwOC1lODlmLTQyZGItYTllZC1mNzc3NDJiOGM1ZWIiLCJuYW1lIjoiU3lzdGVtIiwiZW1haWwiOiJhZG1pbkBib29rc3RvcmUubG9jYWwiLCJpZCI6ImNmOGZhOTA4LWU4OWYtNDJkYi1hOWVkLWY3Nzc0MmI4YzVlYiIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzYxMDA0MTcyLCJpc3MiOiJJZGVudGl0eUJvb2tTdG9yZSIsImF1ZCI6IkJvb2tTdG9yZSJ9.Jip3bAttpX6g6aljnCaPYLHJvaM_2D1rzkyfX172YjU
GET {{baseUrl}}/catalog/api/categories/c26adb77-5068-480e-a8a5-835316170919
Authorization: Bearer {{access_token}}