
@baseUrl = http://localhost:7000
@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1ZmNiODI1OS1mZGJmLTRjNWYtYWRkYS1kMmNhNWIwNDNhNDMiLCJuYW1lIjoiU3lzdGVtIiwiZW1haWwiOiJhZG1pbkBib29rc3RvcmUubG9jYWwiLCJpZCI6IjVmY2I4MjU5LWZkYmYtNGM1Zi1hZGRhLWQyY2E1YjA0M2E0MyIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzYwOTY0ODI4LCJpc3MiOiJJZGVudGl0eUJvb2tTdG9yZSIsImF1ZCI6IkJvb2tTdG9yZSJ9.1QyKWqLh8jO0xhkbHnuv_l6Xwifxf1d1bwKgzc2KgOo

### List categories
GET {{baseUrl}}/catalog/api/categories?PageNumber=1&PageSize=10
Authorization: Bearer {{access_token}}